### environment (local/dev/prod)
spring.profiles.active=local

### application
spring.application.name=my-backend

### 404
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false